const KEY='tryoutReadyComplete2';
const fresh=()=>({name:'My Player',grade:'',tryout:'',workouts:0,minutes:0,streak:0,lastWorkout:'',shots:{all:[0,0],ft:[0,0],right:[0,0],left:[0,0]},skills:{handling:35,shooting:35,finishing:35,defense:35,conditioning:35,iq:35},done:{},history:[],sprints:[],mock:[],notes:'',savedWorkouts:[],activeWorkout:null});
let db=load(), page='home', temp=[0,0], timer=30, interval=null;
function load(){try{return Object.assign(fresh(),JSON.parse(localStorage.getItem(KEY)||'{}'))}catch{return fresh()}} function save(){localStorage.setItem(KEY,JSON.stringify(db))} const pct=(a,b)=>b?Math.round(a/b*100):0; const day=()=>new Date().toISOString().slice(0,10); const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function court(extra=''){return `<div class="court"><svg viewBox="0 0 500 315"><rect width="500" height="315" fill="#d69a54"/><g fill="none" stroke="#fff" stroke-width="4" opacity=".9"><rect x="8" y="8" width="484" height="299"/><path d="M80 8 C80 220 420 220 420 8"/><rect x="180" y="8" width="140" height="125"/><circle cx="250" cy="133" r="58"/><line x1="215" y1="31" x2="285" y2="31"/><circle cx="250" cy="52" r="10"/></g><defs><marker id="arr" markerWidth="10" markerHeight="10" refX="8" refY="3" orient="auto"><path d="M0,0 L0,6 L9,3z" fill="#111"/></marker></defs>${extra}</svg></div>`} const p=(x,y,t='P')=>`<circle cx="${x}" cy="${y}" r="18" fill="#111" stroke="#fff" stroke-width="3"/><text x="${x}" y="${y+5}" text-anchor="middle" fill="#fff" font-size="12">${t}</text>`; const cone=(x,y)=>`<polygon points="${x},${y-13} ${x-11},${y+10} ${x+11},${y+10}" fill="#ff7a00" stroke="#111" stroke-width="2"/>`; const ar=(a,b,c,d)=>`<line x1="${a}" y1="${b}" x2="${c}" y2="${d}" stroke="#111" stroke-width="5" stroke-dasharray="9 7" marker-end="url(#arr)"/>`;
const D=[
['pound','Pound Dribbles','Ball Handling',5,'2 × 50 each hand','Build control and hand strength.',()=>court(p(250,230)+`<circle cx="282" cy="258" r="9" fill="#f47c20"/>`),['Athletic stance: feet wider than shoulders and knees bent.','Pound the ball hard around knee-to-waist height.','Keep the off hand active as a shield.','Eyes forward. Complete 50 right, then 50 left.','Rest 20 seconds and repeat.'],'Push the ball through the floor; fingertips control it.','Standing upright or staring at the ball.'],
['cross','Crossover Attack','Ball Handling',8,'3 × 8 each way','Create separation with change of direction.',()=>court(p(250,270)+cone(250,190)+cone(180,120)+ar(250,250,250,208)+ar(240,180,190,135)),['Attack the cone with speed.','Drop hips before the move.','Cross below the knees.','Push off the outside foot.','Explode for two dribbles after the move.','Repeat both directions.'],'Sell the original direction with eyes and shoulders.','Doing the move fast but not accelerating afterward.'],
['between','Between-the-Legs Attack','Ball Handling',8,'3 × 6 each way','Protect the ball while changing direction.',()=>court(p(250,270)+cone(250,190)+ar(250,250,250,210)+ar(250,180,330,125)),['Approach under control.','Step slightly forward with the opposite foot.','Push the ball between the legs.','Receive it with the opposite hand.','Explode away at game speed.'],'Keep the dribble low and tight.','Standing up during the move.'],
['right','Right-Hand Layup','Finishing',8,'10 makes','Reliable strong-side finishing.',()=>court(p(390,255)+ar(380,235,315,155)+ar(315,155,270,80)),['Attack from the right wing.','Pick up under control.','Step right then left.','Jump from the left foot.','Finish high with the right hand off the glass.','Count makes, not attempts.'],'Eyes find the backboard target early.','Taking off from the wrong foot or throwing the ball.'],
['left','Left-Hand Layup','Finishing',8,'10 makes','Develop the weak hand.',()=>court(p(110,255)+ar(120,235,185,155)+ar(185,155,230,80)),['Attack from the left wing.','Keep the ball in the left hand.','Step left then right.','Jump from the right foot.','Finish with the left hand off the glass.','Make 10.'],'Start slow, master footwork, then add speed.','Switching back to the dominant hand.'],
['mikan','Mikan Drill','Finishing',7,'20 makes','Touch, footwork and finishing around the rim.',()=>court(p(215,90)+ar(215,90,250,55)+ar(250,55,285,90)),['Stand under the basket.','Finish on one side off one foot.','Grab the rebound before it drops.','Step across and finish on the other side.','Continue alternating.'],'Keep the ball high and move continuously.','Bringing the rebound down to the waist.'],
['form','Form Shooting','Shooting',10,'25 makes','Build repeatable mechanics.',()=>court(p(250,145)+ar(250,125,250,65)),['Begin 3–6 feet from the rim.','Balance feet and hips.','Shooting hand under/behind ball; guide hand on side.','Extend elbow and snap wrist.','Hold follow-through until the ball reaches the rim.','Make 25 with clean form.'],'Range only increases when mechanics stay clean.','Guide-hand thumb pushing the ball.'],
['five','Five-Spot Shooting','Shooting',15,'5 makes × 5 spots','Shoot accurately from several locations.',()=>court(p(95,190,'1')+p(165,145,'2')+p(250,155,'3')+p(335,145,'4')+p(405,190,'5')),['Choose a comfortable range.','Make five at Spot 1.','Track every attempt.','Move through all five spots.','Use the same footwork and follow-through.'],'Compete against yesterday’s percentage.','Rushing after a miss.'],
['ft','Pressure Free Throws','Shooting',8,'20 attempts','Build a repeatable pressure routine.',()=>court(p(250,190)+ar(250,170,250,70)),['Use the same pre-shot routine.','Breathe and focus on one target.','Shoot with balanced mechanics.','Hold the follow-through.','Record all 20 attempts.'],'Routine creates calm under pressure.','Changing mechanics after a miss.'],
['slides','Defensive Slides','Defense',7,'5 × 20 sec','Lateral quickness and defensive stance.',()=>court(p(250,235)+ar(240,235,130,235)+ar(260,235,370,235)),['Feet wider than shoulders.','Hips down, chest up.','Push rather than reach with the lead foot.','Do not cross feet.','20 seconds work / 20 seconds rest × 5.'],'Keep the head level while sliding.','Feet clicking together.'],
['close','Closeout + Slide','Defense',8,'10 reps','Contest shots without getting beaten.',()=>court(p(250,270)+p(250,150,'X')+ar(250,250,250,175)),['Start near the paint.','Sprint toward the shooter.','Chop the last few steps.','Hand high, hips low.','React with two defensive slides.','Recover and repeat.'],'Fast approach, controlled arrival.','Flying past the shooter.'],
['box','Box-Out & Rebound','Defense',8,'15 reps','Create rebounding position before pursuing the ball.',()=>court(p(250,160,'D')+p(250,120,'O')+ar(250,160,250,105)),['On the shot, locate the opponent.','Make legal body contact and turn.','Widen stance and hold position.','Find the ball.','Pursue it with two hands and chin it.'],'Hit, find, get.','Watching the ball before making contact.'],
['sprint','Baseline Sprints','Conditioning',10,'6 trips','Repeated basketball sprint capacity.',()=>court(p(80,260)+ar(105,260,420,260)),['Start behind the baseline.','Sprint through the opposite line.','Decelerate safely after crossing.','Recover 45–60 seconds.','Repeat six quality trips.'],'Quality speed matters more than exhaustion.','Turning the last reps into slow jogging.'],
['shuttle','Lane Shuttle','Conditioning',8,'5 rounds','Acceleration, stopping and direction changes.',()=>court(cone(165,230)+cone(335,230)+p(250,260)+ar(245,250,175,230)+ar(175,220,325,220)),['Start in the middle.','Sprint to one marker and touch.','Plant under control.','Accelerate across to the opposite marker.','Return to center.','Rest 40 seconds between rounds.'],'Lower hips before changing direction.','Planting with a locked knee.'],
['triple','Triple Threat + Jab','Basketball IQ',7,'3 × 8 each side','Learn to catch ready to shoot, pass or drive.',()=>court(p(250,190)),['Catch balanced with knees bent.','Ball protected near the hip/chest pocket.','Eyes at the rim.','Jab without moving the pivot foot.','Read imaginary defender, then pass, shoot or drive.'],'Every catch should threaten the defense.','Putting the ball on the floor automatically.'],
['passcut','Pass & Cut','Basketball IQ',8,'12 reps','Organized-team movement after passing.',()=>court(p(120,210,'P')+p(350,180,'T')+ar(140,205,325,185)+ar(120,190,220,90)),['Pass firmly to a partner or target.','Immediately cut hard toward the basket.','Show a target hand.','Finish if the return pass comes.','Clear to open space if it does not.'],'After a pass, move with purpose.','Passing and standing still.']
].map(x=>({id:x[0],title:x[1],cat:x[2],min:x[3],reps:x[4],why:x[5],visual:x[6],steps:x[7],tip:x[8],mistake:x[9]}));

// Curated tutorial videos. YouTube IDs are stored separately so the app can
// embed the player without depending on extra libraries. More tutorials can be
// added here without changing the drill database.
const VIDEO_TUTORIALS={
  cross:{id:'lMl5dnlNdnA',title:'How to Do a Crossover Drill',source:'Howcast'},
  right:{id:'y3EBpd5RdgY',title:'Layup Footwork for Beginners',source:'HoopsKing'},
  left:{id:'y3EBpd5RdgY',title:'Layup Footwork for Beginners',source:'HoopsKing'}
};
function videoTutorial(d){
  let v=VIDEO_TUTORIALS[d.id];
  if(v) return `<section class="videoLesson"><div class="videoHead"><div><div class="eyebrow">VIDEO TUTORIAL</div><h2>Watch It First</h2></div><span class="pill">${v.source}</span></div><div class="videoWrap"><iframe src="https://www.youtube-nocookie.com/embed/${v.id}?rel=0" title="${v.title}" loading="lazy" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe></div><p class="muted videoNote">Watch the movement once, then use the court diagram and coach steps below. Internet is required for the video.</p></section>`;
  let q=encodeURIComponent(d.title+' basketball tutorial');
  return `<section class="videoLesson"><div class="videoHead"><div><div class="eyebrow">VIDEO TUTORIAL</div><h2>Watch It First</h2></div><span class="pill">Tutorial search</span></div><div class="videoPlaceholder"><div class="playIcon">▶</div><b>${d.title}</b><p class="muted">A vetted embedded video has not been assigned to this drill yet. Use the button below to find a demonstration without breaking the workout screen.</p><a class="btn videoLink" target="_blank" rel="noopener" href="https://www.youtube.com/results?search_query=${q}">FIND VIDEO TUTORIAL</a></div></section>`;
}
const PLAN={0:['Recovery',[]],1:['Handles + Finishing',['pound','cross','between','right','left','mikan','slides','sprint','ft']],2:['Shooting + Defense',['pound','form','five','close','box','shuttle','ft']],3:['Weak Hand + Team Play',['pound','between','left','mikan','triple','passcut','slides','sprint']],4:['Game Scoring + Defense',['cross','right','left','five','close','box','shuttle','ft']],5:['Mock Tryout Prep',['pound','cross','right','left','five','slides','close','sprint','ft']],6:['Live Skills + IQ',['pound','between','mikan','form','triple','passcut','ft']]};
const find=id=>D.find(x=>x.id===id), today=()=>PLAN[new Date().getDay()]; function days(){if(!db.tryout)return'--';return Math.max(0,Math.ceil((new Date(db.tryout+'T23:59:59')-new Date())/86400000))} function ready(){let s=Object.values(db.skills).reduce((a,b)=>a+b,0)/6, c=Math.min(100,db.workouts*6), sh=pct(...db.shots.all);return Math.round(s*.65+c*.2+sh*.15)}
function stat(n,l){return `<div class="card stat"><b>${n}</b><span class="muted">${l}</span></div>`} function skill(n,k){let v=db.skills[k];return `<div class="skill"><div class="skillHead"><span>${n}</span><b>${v}%</b></div><div class="bar"><i style="width:${v}%"></i></div></div>`} function workoutRows(ids){return ids.map((id,i)=>{let d=find(id),done=db.done[day()+id];return `<div class="row"><div class="check ${done?'done':''}">${done?'✓':i+1}</div><div class="grow"><b>${d.title}</b><div class="muted">${d.cat} • ${d.reps} • ${d.min} min</div></div><button class="round" onclick="openDrill('${id}')">›</button></div>`}).join('')}
function home(){let [name,ids]=today();main.innerHTML=`<section class="hero"><div class="eyebrow">PLAYER DEVELOPMENT PROGRAM</div><h1>${esc(db.name)}</h1><div class="two"><div><span class="big orange">${days()}</span><div class="muted">DAYS TO TRYOUTS</div></div><div><span class="big">${ready()}%</span><div class="muted">READINESS</div></div></div><div class="progress" style="margin-top:15px"><i style="width:${ready()}%"></i></div></section><div class="grid four">${stat(db.workouts,'Workouts')}${stat(db.minutes,'Minutes')}${stat(pct(...db.shots.all)+'%','Shooting')}${stat(db.streak,'Streak')}</div><h2>Today: ${name}</h2><div class="card">${ids.length?workoutRows(ids)+`<button class="btn" onclick="go('train')">START WORKOUT</button>`:'<p>Recovery day: easy walking, mobility, hydration and sleep.</p>'}</div><h2>Coach Focus</h2>${weak()}<div class="card"><b>Tryout setup</b><label class="tag">Player name</label><input class="field" value="${esc(db.name)}" onchange="db.name=this.value;save();home()"><label class="tag">Grade</label><input class="field" value="${esc(db.grade)}" placeholder="Example: 9th" onchange="db.grade=this.value;save()"><label class="tag">Tryout date</label><input class="field" type="date" value="${db.tryout}" onchange="db.tryout=this.value;save();home()"></div>`}
function weak(){let names={handling:'Ball Handling',shooting:'Shooting',finishing:'Finishing',defense:'Defense',conditioning:'Conditioning',iq:'Basketball IQ'};return `<div class="card">${Object.entries(db.skills).sort((a,b)=>a[1]-b[1]).slice(0,3).map(([k,v])=>`<div class="row"><div class="grow"><b>${names[k]}</b><div class="muted">Priority training area</div></div><span class="pill">${v}%</span></div>`).join('')}</div>`}
function train(){let [defaultName,defaultIds]=today(), w=db.activeWorkout||{name:defaultName,ids:defaultIds,started:day()}; let ids=w.ids||[]; main.innerHTML=`<section class="hero"><div class="eyebrow">ACTIVE WORKOUT</div><h1>${esc(w.name)}</h1><p class="muted">Complete it, save it for later, or save it and start a fresh workout.</p></section><div class="card workoutActions"><button class="btn secondary" onclick="saveWorkoutForLater(false)">💾 SAVE WORKOUT</button><button class="btn" onclick="saveWorkoutForLater(true)">💾 SAVE + NEW WORKOUT</button><button class="btn secondary" onclick="openSavedWorkouts()">📂 SAVED WORKOUTS (${db.savedWorkouts.length})</button></div>${ids.length?`<div class="card">${workoutRows(ids)}</div><button class="btn green" onclick="finishWorkout()">COMPLETE WORKOUT</button>`:'<div class="card"><h2>Recovery Day</h2><p>Light mobility and recovery only.</p></div>'}`}
function snapshotWorkout(){let [defaultName,defaultIds]=today(),w=db.activeWorkout||{name:defaultName,ids:defaultIds};return {id:'w'+Date.now(),name:w.name||defaultName,ids:[...(w.ids||defaultIds)],savedAt:new Date().toISOString(),doneIds:(w.ids||defaultIds).filter(id=>db.done[day()+id])}}
function saveWorkoutForLater(startNew){let w=snapshotWorkout();db.savedWorkouts.unshift(w);save();if(startNew){startNewWorkout()}else{alert('Workout saved. You can reopen it from Saved Workouts.');train()}}
function startNewWorkout(){let [name,ids]=today();db.activeWorkout={name:'New Workout '+(db.savedWorkouts.length+1),ids:[...ids],started:day()};ids.forEach(id=>delete db.done[day()+id]);save();train()}
function openSavedWorkouts(){modalBody.innerHTML=`<div class="eyebrow">WORKOUT LIBRARY</div><h1>Saved Workouts</h1><p class="muted">Resume any saved session without losing the others.</p>${db.savedWorkouts.length?db.savedWorkouts.map(w=>`<div class="card"><div class="row"><div class="grow"><b>${esc(w.name)}</b><div class="muted">Saved ${new Date(w.savedAt).toLocaleString()} • ${w.doneIds.length}/${w.ids.length} drills complete</div></div></div><button class="btn" onclick="resumeWorkout('${w.id}')">RESUME</button><button class="btn red" onclick="deleteSavedWorkout('${w.id}')">DELETE</button></div>`).join(''):'<div class="card"><p>No saved workouts yet.</p></div>'}<button class="btn green" onclick="modal.close();startNewWorkout()">+ START NEW WORKOUT</button>`;modal.showModal()}
function resumeWorkout(id){let w=db.savedWorkouts.find(x=>x.id===id);if(!w)return;db.activeWorkout={name:w.name,ids:[...w.ids],started:day()};w.ids.forEach(d=>delete db.done[day()+d]);w.doneIds.forEach(d=>db.done[day()+d]=1);db.savedWorkouts=db.savedWorkouts.filter(x=>x.id!==id);save();modal.close();go('train')}
function deleteSavedWorkout(id){if(!confirm('Delete this saved workout?'))return;db.savedWorkouts=db.savedWorkouts.filter(x=>x.id!==id);save();openSavedWorkouts()}
function drills(filter='All'){let cats=['All',...new Set(D.map(x=>x.cat))],list=filter==='All'?D:D.filter(x=>x.cat===filter);main.innerHTML=`<section class="hero"><div class="eyebrow">DRILL LIBRARY</div><h1>Learn Every Movement</h1><p class="muted">Each drill includes a court depiction, exact steps, coaching cues and common mistakes.</p></section><div class="card filters">${cats.map(c=>`<button class="pill" onclick="drills('${c}')">${c}</button>`).join('')}</div>${list.map(d=>`<div class="card row"><div class="grow"><b>${d.title}</b><div class="muted">${d.cat} • ${d.reps}</div><div class="tag">${d.why}</div></div><button class="round" onclick="openDrill('${d.id}')">›</button></div>`).join('')}`}
function stats(){let vals=db.history.filter(x=>x.accuracy!=null).slice(0,10).reverse();main.innerHTML=`<section class="hero"><div class="eyebrow">PLAYER DEVELOPMENT</div><div class="score">${ready()}%</div><div style="text-align:center" class="muted">TRYOUT READINESS</div></section><div class="grid four">${stat(pct(...db.shots.all)+'%','All Shots')}${stat(pct(...db.shots.ft)+'%','Free Throws')}${stat(pct(...db.shots.right)+'%','Right Layups')}${stat(pct(...db.shots.left)+'%','Left Layups')}</div><div class="card"><h2>Skill Development</h2>${skill('Ball Handling','handling')}${skill('Shooting','shooting')}${skill('Finishing','finishing')}${skill('Defense','defense')}${skill('Conditioning','conditioning')}${skill('Basketball IQ','iq')}</div><div class="card"><h2>Recent Accuracy</h2>${vals.length?`<div class="chart">${vals.map(x=>`<div style="height:${Math.max(3,x.accuracy)}%"><small>${x.accuracy}%</small></div>`).join('')}</div>`:'<p class="muted">Record shooting sessions to build the chart.</p>'}</div><div class="card"><h2>Personal Records</h2><div class="row"><div class="grow">Best sprint</div><b>${db.sprints.length?Math.min(...db.sprints).toFixed(2)+' sec':'--'}</b></div><div class="row"><div class="grow">Mock tryouts</div><b>${db.mock.length}</b></div><div class="row"><div class="grow">Best mock score</div><b>${db.mock.length?Math.max(...db.mock.map(x=>x.score))+'%':'--'}</b></div></div><h2>Achievements</h2><div class="grid">${achievements()}</div><div class="card"><h2>History</h2>${db.history.slice(0,15).map(h=>`<div class="row"><div class="grow"><b>${h.type}</b><div class="muted">${h.date}</div></div><span>${h.result}</span></div>`).join('')||'<p class="muted">No sessions recorded yet.</p>'}</div>`}
function achievements(){let a=[['First Practice',db.workouts>=1],['5 Workouts',db.workouts>=5],['100 Minutes',db.minutes>=100],['70% Shooting',pct(...db.shots.all)>=70&&db.shots.all[1]>=20],['Weak Hand 70%',pct(...db.shots.left)>=70&&db.shots.left[1]>=10],['Mock Tryout',db.mock.length>0]];return a.map(([n,u])=>`<div class="card stat achievement ${u?'unlocked':''}"><b>${u?'🏆':'🔒'}</b><span>${n}</span></div>`).join('')}
function coach(){main.innerHTML=`<section class="hero"><div class="eyebrow">PARENT / COACH MODE</div><h1>Evaluate What You See</h1><p class="muted">Rate real performance—not potential. Update after pickup games or mock tryouts.</p></section>${Object.entries({handling:'Ball Handling',shooting:'Shooting',finishing:'Finishing',defense:'Defense',conditioning:'Conditioning',iq:'Basketball IQ'}).map(([k,n])=>`<div class="card"><div class="skillHead"><b>${n}</b><span id="v${k}">${db.skills[k]}%</span></div><input style="width:100%" type="range" min="0" max="100" step="5" value="${db.skills[k]}" oninput="document.getElementById('v${k}').textContent=this.value+'%'" onchange="db.skills.${k}=+this.value;save()"></div>`).join('')}<div class="card"><h2>Sprint Timer</h2><p class="muted">Use a stopwatch and save a baseline-to-baseline time.</p><input id="sprintInput" class="field" type="number" step=".01" placeholder="Seconds"><button class="btn" onclick="saveSprint()">SAVE SPRINT TIME</button></div><button class="btn" onclick="mockTryout()">🏀 START MOCK TRYOUT</button><div class="card"><h2>Coach Notes</h2><textarea class="field" rows="5" placeholder="Effort, defense, decisions, attitude..." onchange="db.notes=this.value;save()">${esc(db.notes)}</textarea></div><div class="card"><h2>What Gets Players Noticed</h2><ol><li>Sprint into drills and back on defense.</li><li>Listen while the coach speaks.</li><li>Communicate: ball, help, screen, cutter.</li><li>Make the simple pass and move after passing.</li><li>Box out before chasing rebounds.</li><li>Use both hands and protect the ball.</li><li>Respond to mistakes with the next play—not bad body language.</li><li>Encourage teammates and compete without arguing.</li></ol></div>`}
function openDrill(id){let d=find(id);temp=[0,0];timer=30;modalBody.innerHTML=`<div class="eyebrow">${d.cat.toUpperCase()}</div><h1>${d.title}</h1><p>${d.why}</p>${videoTutorial(d)}${d.visual()}<div class="grid">${stat(d.reps,'WORK')}${stat(d.min,'MINUTES')}</div><h2>Exactly How To Do It</h2><ol>${d.steps.map(s=>`<li>${s}</li>`).join('')}</ol><div class="tip"><b>🏀 Coach cue</b><br>${d.tip}</div><div class="warn"><b>⚠ Common mistake</b><br>${d.mistake}</div><h2>Work Timer</h2><div id="timer" class="timer">00:30</div><div class="two"><button class="btn" onclick="startTimer()">START</button><button class="btn secondary" onclick="resetTimer()">RESET</button></div>${['Shooting','Finishing'].includes(d.cat)?tracker(id):''}<button class="btn green" onclick="completeDrill('${id}')">✓ COMPLETE DRILL</button>`;modal.showModal()}
function tracker(id){return `<h2>Make / Miss Tracker</h2><div class="makeMiss"><button class="make" onclick="shot(true)">✓ MAKE</button><button class="miss" onclick="shot(false)">✕ MISS</button></div><div class="card stat"><b id="shotScore">0 / 0</b><span id="shotPct" class="muted">0% accuracy</span></div><button class="btn secondary" onclick="saveShots('${id}')">SAVE RESULTS</button>`} function shot(make){temp[1]++;if(make)temp[0]++;shotScore.textContent=`${temp[0]} / ${temp[1]}`;shotPct.textContent=pct(...temp)+'% accuracy'}
function saveShots(id){if(!temp[1])return alert('Record at least one attempt.');db.shots.all[0]+=temp[0];db.shots.all[1]+=temp[1];let map={ft:'ft',right:'right',left:'left'},k=map[id];if(k){db.shots[k][0]+=temp[0];db.shots[k][1]+=temp[1]}let d=find(id),sk=d.cat==='Shooting'?'shooting':'finishing';db.skills[sk]=Math.min(100,db.skills[sk]+Math.max(1,Math.round(pct(...temp)/25)));db.history.unshift({date:new Date().toLocaleDateString(),type:d.title,result:`${temp[0]}/${temp[1]} (${pct(...temp)}%)`,accuracy:pct(...temp)});save();alert('Results saved.');temp=[0,0]}
function completeDrill(id){let k=day()+id,d=find(id);if(!db.done[k]){db.done[k]=1;db.minutes+=d.min;let map={'Ball Handling':'handling','Shooting':'shooting','Finishing':'finishing','Defense':'defense','Conditioning':'conditioning','Basketball IQ':'iq'},sk=map[d.cat];db.skills[sk]=Math.min(100,db.skills[sk]+1);db.history.unshift({date:new Date().toLocaleDateString(),type:d.title,result:'Completed'});save()}modal.close();render()}
function finishWorkout(){let [name,ids]=today();if(!ids.every(id=>db.done[day()+id])&&!confirm('Some drills are unfinished. Complete workout anyway?'))return;let k='workout'+day();if(!db.done[k]){db.done[k]=1;db.workouts++;let yesterday=new Date(Date.now()-86400000).toISOString().slice(0,10);db.streak=db.lastWorkout===yesterday?db.streak+1:1;db.lastWorkout=day();db.skills.iq=Math.min(100,db.skills.iq+1);db.history.unshift({date:new Date().toLocaleDateString(),type:'Workout',result:name});save()}db.activeWorkout=null;save();alert('🏀 Practice complete. It has been added to history.');render()}
function startTimer(){clearInterval(interval);interval=setInterval(()=>{timer--;drawTimer();if(timer<=0){clearInterval(interval);navigator.vibrate?.([250,100,250]);alert('Time! Recover for the next rep.')}},1000)} function resetTimer(){clearInterval(interval);timer=30;drawTimer()} function drawTimer(){let e=document.getElementById('timer');if(e)e.textContent=`${String(Math.floor(timer/60)).padStart(2,'0')}:${String(timer%60).padStart(2,'0')}`}
function saveSprint(){let e=document.getElementById('sprintInput'),v=+e.value;if(!v||v<=0)return alert('Enter a sprint time.');db.sprints.push(v);db.skills.conditioning=Math.min(100,db.skills.conditioning+2);db.history.unshift({date:new Date().toLocaleDateString(),type:'Baseline Sprint',result:v.toFixed(2)+' sec'});save();coach()}
function mockTryout(){modalBody.innerHTML=`<div class="eyebrow">GAME-DAY SIMULATION</div><h1>Mock Tryout</h1><p>Run continuously like a coach is evaluating him.</p><div class="card"><ol><li>Dynamic warm-up — 8 min</li><li>Full-court control dribble — 6 trips</li><li>Right layups — 10 attempts</li><li>Left layups — 10 attempts</li><li>Five-spot shooting — 25 attempts</li><li>Defensive slides — 5 × 20 sec</li><li>Closeouts — 10 reps</li><li>Baseline sprints — 6 trips</li><li>Free throws — 10 attempts</li></ol></div><h2>Coach Scores (1–5)</h2>${['Effort','Ball control','Shooting','Finishing','Defense','Conditioning','Communication','Attitude'].map((n,i)=>`<label>${n}</label><select id="m${i}" class="field"><option>1</option><option>2</option><option>3</option><option selected>4</option><option>5</option></select>`).join('')}<button class="btn green" onclick="saveMock()">SAVE MOCK TRYOUT</button>`;modal.showModal()}
function saveMock(){let total=0;for(let i=0;i<8;i++)total+=+document.getElementById('m'+i).value;let score=Math.round(total/40*100);db.mock.push({date:day(),score});db.history.unshift({date:new Date().toLocaleDateString(),type:'Mock Tryout',result:score+'%'});Object.keys(db.skills).forEach(k=>db.skills[k]=Math.min(100,db.skills[k]+1));save();modal.close();alert(`Mock tryout score: ${score}%`);go('stats')}
function settings(){modalBody.innerHTML=`<h1>Settings & Data</h1><p class="muted">Progress is saved in this browser using localStorage.</p><button class="btn" onclick="exportData()">EXPORT BACKUP</button><label class="btn secondary" style="display:block;text-align:center">IMPORT BACKUP<input type="file" accept="application/json" hidden onchange="importData(this.files[0])"></label><button class="btn red" onclick="resetAll()">RESET ALL DATA</button><div class="tip"><b>Backup tip:</b> Export the data occasionally. Browser storage can be cleared if site data is erased.</div>`;modal.showModal()}
function exportData(){let blob=new Blob([JSON.stringify(db,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='tryout-ready-backup.json';a.click();URL.revokeObjectURL(a.href)} function importData(f){if(!f)return;let r=new FileReader;r.onload=()=>{try{db=Object.assign(fresh(),JSON.parse(r.result));save();modal.close();render();alert('Backup restored.')}catch{alert('That backup file is not valid.')}};r.readAsText(f)} function resetAll(){if(confirm('Delete ALL player progress? This cannot be undone.')){db=fresh();save();modal.close();render()}}
function go(p){page=p;document.querySelectorAll('#nav button').forEach(b=>b.classList.toggle('active',b.dataset.page===p));render()} function render(){({home,train,drills,stats,coach}[page]||home)();scrollTo(0,0)}
document.querySelectorAll('#nav button').forEach(b=>b.onclick=()=>go(b.dataset.page));settingsBtn.onclick=settings;closeModal.onclick=()=>modal.close();modal.addEventListener('close',()=>clearInterval(interval));go('home');
